namespace SmartSpendAI.Models
{
    public class JwtSettings
    {
        public const string SectionName = "Jwt";

        public string Issuer { get; set; } = "SmartSpendAI";

        public string Audience { get; set; } = "SmartSpendAIClient";

        public string SecretKey { get; set; } = string.Empty;

        public bool UseAsymmetric { get; set; }

        public string PrivateKeyPem { get; set; } = string.Empty;

        public string PublicKeyPem { get; set; } = string.Empty;

        public string PrivateKeyPemPath { get; set; } = string.Empty;

        public string PublicKeyPemPath { get; set; } = string.Empty;

        public bool AutoGenerateDevelopmentKey { get; set; } = true;

        public int GeneratedKeySize { get; set; } = 2048;

        public int AccessTokenMinutes { get; set; } = 60;

        public int RememberMeAccessTokenDays { get; set; } = 7;
    }
}
