// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSpendAI.Models;

#nullable disable

namespace SmartSpendAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326010448_AddUserAvatarUrl")]
    partial class AddUserAvatarUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSpendAI.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BudgetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId", "Month")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.BudgetAlert", b =>
                {
                    b.Property<int>("BudgetAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetAlertId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BudgetAlertId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("BudgetAlerts", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Color = "#ff7a18",
                            Icon = "utensils",
                            IsSystem = true,
                            Name = "An uong",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 2,
                            Color = "#00b894",
                            Icon = "car",
                            IsSystem = true,
                            Name = "Di chuyen",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 3,
                            Color = "#6c5ce7",
                            Icon = "film",
                            IsSystem = true,
                            Name = "Giai tri",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 4,
                            Color = "#ff4d4f",
                            Icon = "receipt",
                            IsSystem = true,
                            Name = "Hoa don",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 5,
                            Color = "#0097e6",
                            Icon = "bag",
                            IsSystem = true,
                            Name = "Mua sam",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Color = "#2ecc71",
                            Icon = "wallet",
                            IsSystem = true,
                            Name = "Luong",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 7,
                            Color = "#00cec9",
                            Icon = "sparkles",
                            IsSystem = true,
                            Name = "Thuong",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 8,
                            Color = "#95a5a6",
                            Icon = "circle",
                            IsSystem = true,
                            Name = "Khac",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("SmartSpendAI.Models.EmailVerificationOtp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OtpSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RequestedIp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.HasIndex("Email", "Purpose", "IsUsed", "ExpiresAt");

                    b.ToTable("EmailVerificationOtps");
                });

            modelBuilder.Entity("SmartSpendAI.Models.KeywordEntry", b =>
                {
                    b.Property<int>("KeywordEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordEntryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KeywordEntryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Word");

                    b.ToTable("Keywords", (string)null);

                    b.HasData(
                        new
                        {
                            KeywordEntryId = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Weight = 10,
                            Word = "tra sua"
                        },
                        new
                        {
                            KeywordEntryId = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Weight = 8,
                            Word = "an vat"
                        },
                        new
                        {
                            KeywordEntryId = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Weight = 7,
                            Word = "com"
                        },
                        new
                        {
                            KeywordEntryId = 4,
                            CategoryId = 2,
                            IsActive = true,
                            Weight = 10,
                            Word = "xang"
                        },
                        new
                        {
                            KeywordEntryId = 5,
                            CategoryId = 2,
                            IsActive = true,
                            Weight = 9,
                            Word = "grab"
                        },
                        new
                        {
                            KeywordEntryId = 6,
                            CategoryId = 2,
                            IsActive = true,
                            Weight = 8,
                            Word = "xe bus"
                        },
                        new
                        {
                            KeywordEntryId = 7,
                            CategoryId = 3,
                            IsActive = true,
                            Weight = 10,
                            Word = "xem phim"
                        },
                        new
                        {
                            KeywordEntryId = 8,
                            CategoryId = 3,
                            IsActive = true,
                            Weight = 8,
                            Word = "karaoke"
                        },
                        new
                        {
                            KeywordEntryId = 9,
                            CategoryId = 4,
                            IsActive = true,
                            Weight = 8,
                            Word = "dien"
                        },
                        new
                        {
                            KeywordEntryId = 10,
                            CategoryId = 4,
                            IsActive = true,
                            Weight = 8,
                            Word = "nuoc"
                        },
                        new
                        {
                            KeywordEntryId = 11,
                            CategoryId = 4,
                            IsActive = true,
                            Weight = 7,
                            Word = "wifi"
                        },
                        new
                        {
                            KeywordEntryId = 12,
                            CategoryId = 6,
                            IsActive = true,
                            Weight = 10,
                            Word = "luong"
                        },
                        new
                        {
                            KeywordEntryId = 13,
                            CategoryId = 7,
                            IsActive = true,
                            Weight = 10,
                            Word = "thuong"
                        });
                });

            modelBuilder.Entity("SmartSpendAI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "StandardUser"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("SmartSpendAI.Models.TransactionEntry", b =>
                {
                    b.Property<int>("TransactionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionEntryId"));

                    b.Property<decimal>("AiConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ReceiptImagePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionEntryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "TransactionDate");

                    b.HasIndex("WalletId", "TransactionDate");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.TransferRecord", b =>
                {
                    b.Property<int>("TransferRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferRecordId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromWalletId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<int>("ToWalletId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransferRecordId");

                    b.HasIndex("FromWalletId");

                    b.HasIndex("ToWalletId");

                    b.ToTable("Transfers", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartSpendAI.Models.UserPersonalKeyword", b =>
                {
                    b.Property<int>("UserPersonalKeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPersonalKeywordId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPersonalKeywordId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "Keyword")
                        .IsUnique();

                    b.ToTable("UserPersonalKeywords", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("SmartSpendAI.Models.AuditLog", b =>
                {
                    b.HasOne("SmartSpendAI.Models.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("SmartSpendAI.Models.Budget", b =>
                {
                    b.HasOne("SmartSpendAI.Models.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartSpendAI.Models.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSpendAI.Models.BudgetAlert", b =>
                {
                    b.HasOne("SmartSpendAI.Models.TransactionEntry", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSpendAI.Models.User", "User")
                        .WithMany("BudgetAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSpendAI.Models.EmailVerificationOtp", b =>
                {
                    b.HasOne("SmartSpendAI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSpendAI.Models.KeywordEntry", b =>
                {
                    b.HasOne("SmartSpendAI.Models.Category", "Category")
                        .WithMany("Keywords")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartSpendAI.Models.TransactionEntry", b =>
                {
                    b.HasOne("SmartSpendAI.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartSpendAI.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartSpendAI.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SmartSpendAI.Models.TransferRecord", b =>
                {
                    b.HasOne("SmartSpendAI.Models.Wallet", "FromWallet")
                        .WithMany("OutgoingTransfers")
                        .HasForeignKey("FromWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartSpendAI.Models.Wallet", "ToWallet")
                        .WithMany("IncomingTransfers")
                        .HasForeignKey("ToWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromWallet");

                    b.Navigation("ToWallet");
                });

            modelBuilder.Entity("SmartSpendAI.Models.User", b =>
                {
                    b.HasOne("SmartSpendAI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartSpendAI.Models.UserPersonalKeyword", b =>
                {
                    b.HasOne("SmartSpendAI.Models.Category", "Category")
                        .WithMany("PersonalKeywords")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSpendAI.Models.User", "User")
                        .WithMany("PersonalKeywords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSpendAI.Models.Wallet", b =>
                {
                    b.HasOne("SmartSpendAI.Models.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSpendAI.Models.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Keywords");

                    b.Navigation("PersonalKeywords");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartSpendAI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartSpendAI.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BudgetAlerts");

                    b.Navigation("Budgets");

                    b.Navigation("PersonalKeywords");

                    b.Navigation("Transactions");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("SmartSpendAI.Models.Wallet", b =>
                {
                    b.Navigation("IncomingTransfers");

                    b.Navigation("OutgoingTransfers");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
