using System.Security.Cryptography;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using SmartSpendAI.Models;

namespace SmartSpendAI.Security
{
    public sealed class JwtSigningMaterial
    {
        public SecurityKey SigningKey { get; }

        public SecurityKey ValidationKey { get; }

        public string Algorithm { get; }

        public bool IsAsymmetric { get; }

        public bool IsEphemeral { get; }

        private JwtSigningMaterial(
            SecurityKey signingKey,
            SecurityKey validationKey,
            string algorithm,
            bool isAsymmetric,
            bool isEphemeral)
        {
            SigningKey = signingKey;
            ValidationKey = validationKey;
            Algorithm = algorithm;
            IsAsymmetric = isAsymmetric;
            IsEphemeral = isEphemeral;
        }

        public SigningCredentials CreateSigningCredentials()
        {
            return new SigningCredentials(SigningKey, Algorithm);
        }

        public static JwtSigningMaterial Create(JwtSettings settings, string contentRootPath)
        {
            if (settings.UseAsymmetric)
            {
                return CreateAsymmetric(settings, contentRootPath);
            }

            return CreateSymmetric(settings);
        }

        private static JwtSigningMaterial CreateSymmetric(JwtSettings settings)
        {
            if (string.IsNullOrWhiteSpace(settings.SecretKey))
            {
                throw new InvalidOperationException("Jwt:SecretKey is required when Jwt:UseAsymmetric=false.");
            }

            var keyBytes = Encoding.UTF8.GetBytes(settings.SecretKey);
            if (keyBytes.Length < 32)
            {
                throw new InvalidOperationException("Jwt:SecretKey must be at least 32 bytes.");
            }

            var key = new SymmetricSecurityKey(keyBytes);
            return new JwtSigningMaterial(
                key,
                key,
                SecurityAlgorithms.HmacSha256,
                isAsymmetric: false,
                isEphemeral: false);
        }

        private static JwtSigningMaterial CreateAsymmetric(JwtSettings settings, string contentRootPath)
        {
            var privateKeyPem = ResolvePem(
                settings.PrivateKeyPem,
                settings.PrivateKeyPemPath,
                contentRootPath);

            var publicKeyPem = ResolvePem(
                settings.PublicKeyPem,
                settings.PublicKeyPemPath,
                contentRootPath);

            if (string.IsNullOrWhiteSpace(privateKeyPem))
            {
                if (!settings.AutoGenerateDevelopmentKey)
                {
                    throw new InvalidOperationException(
                        "Jwt asymmetric mode is enabled but private key is missing. Set Jwt:PrivateKeyPem or Jwt:PrivateKeyPemPath.");
                }

                var generated = RSA.Create(Math.Max(2048, settings.GeneratedKeySize));
                var signingKey = new RsaSecurityKey(generated.ExportParameters(true));
                var validationKey = new RsaSecurityKey(generated.ExportParameters(false));

                return new JwtSigningMaterial(
                    signingKey,
                    validationKey,
                    SecurityAlgorithms.RsaSha256,
                    isAsymmetric: true,
                    isEphemeral: true);
            }

            using var privateRsa = RSA.Create();
            privateRsa.ImportFromPem(privateKeyPem);

            var signingRsa = RSA.Create();
            signingRsa.ImportParameters(privateRsa.ExportParameters(true));

            RSA validationRsa;
            if (string.IsNullOrWhiteSpace(publicKeyPem))
            {
                validationRsa = RSA.Create();
                validationRsa.ImportParameters(privateRsa.ExportParameters(false));
            }
            else
            {
                validationRsa = RSA.Create();
                validationRsa.ImportFromPem(publicKeyPem);
            }

            var signingSecurityKey = new RsaSecurityKey(signingRsa);
            var validationSecurityKey = new RsaSecurityKey(validationRsa);

            return new JwtSigningMaterial(
                signingSecurityKey,
                validationSecurityKey,
                SecurityAlgorithms.RsaSha256,
                isAsymmetric: true,
                isEphemeral: false);
        }

        private static string ResolvePem(string inlinePem, string pemPath, string contentRootPath)
        {
            if (!string.IsNullOrWhiteSpace(inlinePem))
            {
                return inlinePem.Trim();
            }

            if (string.IsNullOrWhiteSpace(pemPath))
            {
                return string.Empty;
            }

            var normalizedPath = Path.IsPathRooted(pemPath)
                ? pemPath
                : Path.Combine(contentRootPath, pemPath);

            if (!File.Exists(normalizedPath))
            {
                return string.Empty;
            }

            return File.ReadAllText(normalizedPath).Trim();
        }
    }
}
